apiVersion: v1
kind: Secret
metadata:
  name: radius-db-secret
  namespace: free-radius
  labels:
    app: free-radius
    env: production
    tier: backend
type: Opaque
stringData:
  # Ganti dengan kredensial database external Anda
  DB_HOST: "postgres.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "radius"
  DB_PASSWORD: "radpass"
  DB_NAME: "radius"
  # Shared secret untuk localhost/internal testing
  RADIUS_LOCALHOST_SECRET: "testing123"
